

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - utsiae-network

  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - utsiae-network

  product-db:
    image: mysql:8
    container_name: product-db
    environment:
      MYSQL_DATABASE: laundry_product_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - utsiae-network

  order-db:
    image: mysql:8
    container_name: order-db
    environment:
      MYSQL_DATABASE: laundry_order_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    networks:
      - utsiae-network

  payment-db:
    image: mysql:8
    container_name: payment-db
    environment:
      MYSQL_DATABASE: laundry_payment_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    networks:
      - utsiae-network

  user-service:
    build: ./UserService
    ports:
      - "8001:8000"
    depends_on:
      - user-db
    networks:
      - utsiae-network

  product-service:
    build: ./ProductService
    ports:
      - "8002:8000"
    depends_on:
      - product-db
      - rabbitmq
    networks:
      - utsiae-network

  product-worker:
    build: ./ProductService
    command: php artisan queue:work rabbitmq --sleep=3 --tries=3
    depends_on:
      - product-db
      - rabbitmq
    networks:
      - utsiae-network

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    depends_on:
      - order-db
      - rabbitmq
    networks:
      - utsiae-network

  payment-service:
    build: ./payment-service
    ports:
      - "8004:8000"
    depends_on:
      - payment-db
      - rabbitmq
    networks:
      - utsiae-network

networks:
  utsiae-network:
    driver: bridge